#Sponge launch configuration
#Wed Feb 25 18:30:26 GMT 2026
additional-plugins-directory=${MODS_DIR}/plugins
args=--nogui
auto-download-libraries=true
check-library-hashes=true
libraries-directory=${BASE_DIR}/libraries
